<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Rdiffweb-discuss] error 500
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/rdiffweb-discuss/2008-January/index.html" >
   <LINK REL="made" HREF="mailto:rdiffweb-discuss%40lists.berlios.de?Subject=Re%3A%20%5BRdiffweb-discuss%5D%20error%20500&In-Reply-To=%3C479E7876.7000501%40joshnisly.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000201.html">
   <LINK REL="Next"  HREF="000204.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Rdiffweb-discuss] error 500</H1>
    <B>Josh Nisly</B> 
    <A HREF="mailto:rdiffweb-discuss%40lists.berlios.de?Subject=Re%3A%20%5BRdiffweb-discuss%5D%20error%20500&In-Reply-To=%3C479E7876.7000501%40joshnisly.com%3E"
       TITLE="[Rdiffweb-discuss] error 500">rdiffweb at joshnisly.com
       </A><BR>
    <I>Tue Jan 29 01:51:02 CET 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="000201.html">[Rdiffweb-discuss] error 500
</A></li>
        <LI>Next message: <A HREF="000204.html">[Rdiffweb-discuss] error 500
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#202">[ date ]</a>
              <a href="thread.html#202">[ thread ]</a>
              <a href="subject.html#202">[ subject ]</a>
              <a href="author.html#202">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>This is the often-reported bug with encoding non-ascii characters. I've 
committed several fixes to the latest svn that should fix this problem. 
Could you please test with the latest subversion code to see if it works 
for you?

Thanks,
JoshN

Christoph Langbein wrote:
&gt;<i> Hello,
</I>&gt;<i> I've setup rdiffWeb-0.6.1 last week using cherryPy 3.0.3 on debian etch,
</I>&gt;<i> python2.5. two &quot;old&quot; backups used with rdiffWeb-0.3.5.1 working as
</I>&gt;<i> expected.
</I>&gt;<i> Now I've created a new backup and get following error when selecting it:
</I>&gt;<i> 500 Internal Server Error
</I>&gt;<i> The server encountered an unexpected condition which prevented it from
</I>&gt;<i> fulfilling the request.
</I>&gt;<i>
</I>&gt;<i> Traceback (most recent call last):
</I>&gt;<i>   File &quot;/usr/lib/python2.5/site-packages/cherrypy/_cprequest.py&quot;, line 551, in respond
</I>&gt;<i>     cherrypy.response.body = self.handler()
</I>&gt;<i>   File &quot;/usr/lib/python2.5/site-packages/cherrypy/_cpdispatch.py&quot;, line 24, in __call__
</I>&gt;<i>     return self.callable(*self.args, **self.kwargs)
</I>&gt;<i>   File &quot;/usr/lib/python2.5/site-packages/rdiffWeb/page_browse.py&quot;, line 23, in index
</I>&gt;<i>     parms = self.getParmsForPage(self.getUserDB().getUserRoot(self.getUsername()), repo, path, restore)
</I>&gt;<i>   File &quot;/usr/lib/python2.5/site-packages/rdiffWeb/page_browse.py&quot;, line 75, in getParmsForPage
</I>&gt;<i>     entryLink = self.buildBrowseUrl(repo, joinPaths(path, libEntry.name), False)
</I>&gt;<i>   File &quot;/usr/lib/python2.5/site-packages/rdiffWeb/page_main.py&quot;, line 15, in buildBrowseUrl
</I>&gt;<i>     url = &quot;/browse/?repo=&quot;+rdw_helpers.encodeUrl(repo, &quot;/&quot;)+&quot;&amp;path=&quot;+rdw_helpers.encodeUrl(path, &quot;/&quot;)
</I>&gt;<i>   File &quot;/usr/lib/python2.5/site-packages/rdiffWeb/rdw_helpers.py&quot;, line 28, in encodeUrl
</I>&gt;<i>     return urllib.quote_plus(url, safeChars)
</I>&gt;<i>   File &quot;urllib.py&quot;, line 1205, in quote_plus
</I>&gt;<i>     return quote(s, safe)
</I>&gt;<i>   File &quot;urllib.py&quot;, line 1197, in quote
</I>&gt;<i>     res = map(safe_map.__getitem__, s)
</I>&gt;<i> KeyError: u'\xdf'
</I>&gt;<i>
</I>&gt;<i> and in the admin panel, when using &quot;save changes&quot;:
</I>&gt;<i> Traceback (most recent call last):
</I>&gt;<i>   File &quot;/usr/lib/python2.5/site-packages/cherrypy/_cprequest.py&quot;, line 551, in respond
</I>&gt;<i>     cherrypy.response.body = self.handler()
</I>&gt;<i>   File &quot;/usr/lib/python2.5/site-packages/cherrypy/_cpdispatch.py&quot;, line 24, in __call__
</I>&gt;<i>     return self.callable(*self.args, **self.kwargs)
</I>&gt;<i>   File &quot;/usr/lib/python2.5/site-packages/rdiffWeb/page_admin.py&quot;, line 21, in index
</I>&gt;<i>     password = cherrypy.request.params[&quot;password&quot;]
</I>&gt;<i> KeyError: 'password'
</I>&gt;<i>
</I>&gt;<i> Maybe some has an idea what to do?
</I>&gt;<i> Thanks in advance
</I>&gt;<i> Christoph
</I>&gt;<i>
</I>&gt;<i> _______________________________________________
</I>&gt;<i> Rdiffweb-discuss mailing list
</I>&gt;<i> <A HREF="https://lists.berlios.de/mailman/listinfo/rdiffweb-discuss">Rdiffweb-discuss at lists.berlios.de</A>
</I>&gt;<i> <A HREF="https://lists.berlios.de/mailman/listinfo/rdiffweb-discuss">https://lists.berlios.de/mailman/listinfo/rdiffweb-discuss</A>
</I>&gt;<i>
</I>&gt;<i>   
</I>

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000201.html">[Rdiffweb-discuss] error 500
</A></li>
	<LI>Next message: <A HREF="000204.html">[Rdiffweb-discuss] error 500
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#202">[ date ]</a>
              <a href="thread.html#202">[ thread ]</a>
              <a href="subject.html#202">[ subject ]</a>
              <a href="author.html#202">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/rdiffweb-discuss">More information about the Rdiffweb-discuss
mailing list</a><br>
</body></html>
